### ISSUE TITLE
Terraform plan fails due to invalid JSON

### ISSUE THREAD

**Issue by mwkaufman** [dowjones/hammer#86]
Terraform v0.11.14
+ provider.aws v2.16.0
+ provider.template v2.1.2

Error running plan: 1 error occurred:
* module.roles-crossaccount.aws_cloudformation_stack.identification_crossaccount_role: "template_body" contains an invalid JSON: invalid character ']' looking for beginning of value

**Comment by pranav1688** [comment]
Thanks @mwkaufman  for the solution you provided. We have merged the fix
